/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
