/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
