/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl;

import com.google.inject.Binder;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.xtext.example.mydsl.AbstractMyDslRuntimeModule;
import org.xtext.example.mydsl.output.MyOutputConfigProvider;
import org.xtext.example.mydsl.output.OutputConfigurationAwaredGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.<IOutputConfigurationProvider>bind(IOutputConfigurationProvider.class).to(MyOutputConfigProvider.class);
  }
  
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return OutputConfigurationAwaredGenerator.class;
  }
}
